apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging
resources:
  - ../../base
patches:
  - target: {kind: Namespace, name: app}
    patch: |
      - op: replace
        path: /metadata/name
        value: staging
  - target: {kind: ConfigMap, name: app-config}
    patch: |
      - op: replace
        path: /data/ENVIRONMENT
        value: staging
  - target: {kind: Deployment, name: app}
    patch: |
      - op: replace
        path: /spec/replicas
        value: 1
  - target: {kind: HorizontalPodAutoscaler, name: app}
    patch: |
      - op: replace
        path: /spec/minReplicas
        value: 1
      - op: replace
        path: /spec/maxReplicas
        value: 3
images:
  - name: app
    newName: app
    newTag: v4
